name: Build and Deploy to Firebase

on:
  push:
    branches:
      - master  # 此處的分支名稱取決於您要觸發部署的分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js and npm
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # 設置您想要使用的 Node.js 版本

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Deploy to Firebase
      uses: w9jds/firebase-action@v2
      with:
        args: deploy --only hosting  # 部署 Firebase Hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}  # 設置 Firebase token（在下一步中設置）

